create table if not exists system_country
(
    country_id varchar(2)   not null
        constraint system_country_pk
            primary key,
    name       varchar(255) not null
);

create sequence if not exists system_province_province_id_seq minvalue 1 start with 1;
create table if not exists system_province
(
    province_id int generated by default as sequence system_province_province_id_seq not null primary key,
    country_id varchar(2) not null
        constraint system_province_country
            references system_country,
    name       varchar(255) not null
);

create sequence if not exists system_doctor_specialty_specialty_id_seq minvalue 1 start with 1;
create table if not exists system_doctor_specialty
(
    specialty_id int generated by default as sequence system_doctor_specialty_specialty_id_seq not null primary key,
    name varchar(255)     not null
);

create sequence if not exists system_locality_locality_id_seq minvalue 1 start with 1;
create table if not exists system_locality
(
    province_id integer not null
        constraint system_locality_province
            references system_province,
    name        varchar(255) not null,
    locality_id int generated by default as sequence system_locality_locality_id_seq not null primary key
);

create sequence if not exists office_office_id_seq minvalue 1 start with 1;
create table if not exists office
(
    office_id int generated by default as sequence office_office_id_seq not null primary key,
    name        varchar(255) not null,
    street      varchar(255) not null,
    locality_id integer not null
        constraint office_province_id
            references system_locality,
    phone       varchar(255),
    email       varchar(255),
    url         varchar(255)
);

create sequence if not exists picture_picture_id_seq minvalue 1 start with 1;
create table if not exists picture
(
    picture_id int generated by default as sequence picture_picture_id_seq not null primary key,
    name      varchar(1023),
    mime_type varchar(255)     not null,
    size      bigint           not null default 0,
    data      varbinary(65535) not null
);

create sequence if not exists users_users_id_seq minvalue 1 start with 1;
create table if not exists users
(
    email              varchar(255) not null,
    password           varchar(255) not null,
    users_id int generated by default as sequence users_users_id_seq not null primary key,
    first_name         varchar(255) not null,
    surname            varchar(255) not null,
    phone              varchar(255),
    verified           boolean default false,
    verification_token_id              int,
    refresh_token_id             int,
    profile_id         int
        constraint users_picture_picture_id_fk
            foreign key references picture
                on delete set null
);

create sequence if not exists doctor_doctor_id_seq minvalue 1 start with 1;
create table if not exists doctor
(
    doctor_id int generated by default as sequence doctor_doctor_id_seq not null primary key,
    office_id           integer not null
        constraint doctor_office
            references office,
    phone               varchar(255),
    email               varchar(255),
    registration_number integer,
    user_id             integer not null
        constraint doctor_users_users_id_fk
            references users
);

create sequence if not exists picture_picture_id_seq minvalue 1 start with 1;
create table if not exists system_doctor_specialty_doctor
(
    specialty_id integer not null
        constraint specialty_doctor_system_specialty
            references system_doctor_specialty,
    doctor_id     integer not null
        constraint specialty_doctor_doctor
            references doctor,
    constraint system_doctor_specialty_doctor_pk
        primary key (specialty_id, doctor_id)
);

create sequence if not exists patient_patient_id_seq minvalue 1 start with 1;
create table if not exists patient
(
    user_id   integer not null
        constraint patient_user_user_id_fk
            references users,
    office_id integer   not null
        constraint patient_office_office_id_fk
            references office,
    patient_id int generated by default as sequence patient_patient_id_seq not null primary key
);

create sequence if not exists appointment_appointment_id_seq minvalue 1 start with 1;
create table if not exists appointment
(
    appointment_id int generated by default as sequence appointment_appointment_id_seq not null primary key,
    patient_id integer      not null
        constraint appointment_patient_patient_id_fk
            references patient
            on delete cascade
            ,
    doctor_id   integer      not null
        constraint appointment_doctor_doctor_id_fk
            foreign key references doctor
                on delete cascade,
    from_date  timestamp WITHOUT TIME ZONE not null,
    status     varchar(20),
    motive     varchar(65535) not null,
    message    varchar(65535),
    locale      varchar(65535) not null,
    was_notification_email_sent boolean not null default false
);

create sequence if not exists workday_workday_id_seq minvalue 1 start with 1;
create table if not exists workday
(
    workday_id int generated by default as sequence workday_workday_id_seq not null primary key,
    doctor_id     int          not null
        constraint workday_doctor_doctor_id_fk
            references doctor
            on delete cascade,
    start_hour   int          not null,
    end_hour     int          not null,
    start_minute int          not null default 0,
    end_minute   int          not null default 0,
    day          varchar(255) not null
);

create sequence if not exists verification_token_verification_token_id_seq minvalue 1 start with 1;
create table if not exists verification_token
(
    verification_token_id int generated by default as sequence verification_token_verification_token_id_seq not null primary key,
    token text not null,
    created_date timestamp not null
);

create sequence if not exists refresh_token_refresh_token_id_seq minvalue 1 start with 1;
create table if not exists refresh_token
(
    refresh_token_id int generated by default as sequence verification_token_verification_token_id_seq not null primary key,
    token text not null,
    created_date timestamp not null
);

drop function unaccent if exists;
create function unaccent(t varchar(255))
    returns varchar(255)
    return translate(t,
                     'âãäåāăąÁÂÃÄÅĀĂĄèééêëēĕėęěĒĔĖĘĚìíîïìĩīĭÌÍÎÏÌĨĪĬóôõöōŏőÒÓÔÕÖŌŎŐùúûüũūŭůÙÚÛÜŨŪŬŮ',
                     'aaaaaaaaaaaaaaaeeeeeeeeeeeeeeeiiiiiiiiiiiiiiiiooooooooooooooouuuuuuuuuuuuuuuu');
